In [34]:
import tensorflow as tf

In [35]:
a= tf.constant(1)

In [36]:
b=tf.constant(2)

In [37]:
c= a+b 

In [38]:
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [39]:
d= a*b

In [40]:
V1= tf.constant([1.,2.])

In [41]:
V2=tf.constant([3.,4.])

In [42]:
M=tf.constant([[1.,2.]])

In [43]:
N= tf.constant([[1.,2.],[3.,4.]])

In [44]:
V3=V1 + V2

In [45]:
print(V3)

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [46]:
K= tf.constant([[[1.,2.],[3.,4.]]]) #tensor 3d

In [47]:
print(K)

tf.Tensor(
[[[1. 2.]
  [3. 4.]]], shape=(1, 2, 2), dtype=float32)


In [48]:
V3=V1 + V2

In [49]:
print(V3)

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [50]:
M2 = M*M

In [51]:
print(M2)

tf.Tensor([[1. 4.]], shape=(1, 2), dtype=float32)


In [52]:
NN = tf.matmul(N,N)

In [53]:
print(NN)

tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [54]:
sess = tf.compat.v1.InteractiveSession(
    target='', graph=None, config=None
)

In [55]:
#output = sess.run(tf.matmul(N,N))

In [56]:
sess.close()

In [69]:
#sess_v2 = Session(graph)

NameError: name 'Session' is not defined

In [57]:
#print(M2.eval()) #NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

In [58]:
W = tf.Variable(NN)

In [59]:
init_op =tf.compat.v1.initialize_all_variables()

In [60]:
#init_op_global = tf.global_variables_initializer()

In [61]:
#print(W.eval())

In [62]:
W=tf.Variable(0,name="weight")

In [63]:
#init_op = tf.initialize_all_variables()

In [64]:
s = tf.compat.v1.Session()
with tf.compat.v1.get_default_graph().as_default():
  h = tf.constant(NN)
  print(s.run(h))

[[ 7. 10.]
 [15. 22.]]


In [65]:
h = tf.constant(NN)
print(tf.print(h))

[[7 10]
 [15 22]]
None


In [66]:
print(M2.numpy())

[[1. 4.]]
