In [3]:
#import tensorflow as tf 
import numpy as np  

In [4]:
%autoindent

UsageError: Line magic function `%autoindent` not found.


In [5]:
try:
    from tqdm import tqdm
except ImportError:
    def tqdm(x, *args, **kwargs):
        return x

In [6]:
data = np.load('data_with_labels.npz')
train = data['arr_0']/255.
labels = data['arr_1']

In [7]:
print(train[0])
print(labels[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0


In [8]:
import matplotlib.pyplot as plt 
plt.ion()

In [9]:
plt.figure(figsize=(6,6))
f, plts = plt.subplots(5,sharex=True)
c= 91 
for i in range(5):
    plts[i].pcolor(train[c+i*558],cmap=plt.cm.gray_r )

<Figure size 432x432 with 0 Axes>